#include <node_api.h>

#include "Factory.h"

#include "inc/SystemWrapper.h"
#include "inc/CommentWrapper.h"
#include "inc/ModuleDeclarationWrapper.h"
#include "inc/VariableDeclaratorWrapper.h"
#include "inc/PropertyWrapper.h"
#include "inc/SpreadElementWrapper.h"
#include "inc/SuperWrapper.h"
#include "inc/TemplateElementWrapper.h"
#include "inc/CatchClauseWrapper.h"
#include "inc/FunctionWrapper.h"
#include "inc/SwitchCaseWrapper.h"
#include "inc/ClassBodyWrapper.h"
#include "inc/MethodDefinitionWrapper.h"
#include "inc/ProgramWrapper.h"
#include "inc/IdentifierWrapper.h"
#include "inc/ExportNamedDeclarationWrapper.h"
#include "inc/ImportDeclarationWrapper.h"
#include "inc/ArrayExpressionWrapper.h"
#include "inc/ArrowFunctionExpressionWrapper.h"
#include "inc/AssignmentExpressionWrapper.h"
#include "inc/AwaitExpressionWrapper.h"
#include "inc/BinaryExpressionWrapper.h"
#include "inc/CallExpressionWrapper.h"
#include "inc/ClassExpressionWrapper.h"
#include "inc/ConditionalExpressionWrapper.h"
#include "inc/FunctionExpressionWrapper.h"
#include "inc/LogicalExpressionWrapper.h"
#include "inc/MemberExpressionWrapper.h"
#include "inc/MetaPropertyWrapper.h"
#include "inc/NewExpressionWrapper.h"
#include "inc/ObjectExpressionWrapper.h"
#include "inc/SequenceExpressionWrapper.h"
#include "inc/TaggedTemplateExpressionWrapper.h"
#include "inc/TemplateLiteralWrapper.h"
#include "inc/ThisExpressionWrapper.h"
#include "inc/UnaryExpressionWrapper.h"
#include "inc/UpdateExpressionWrapper.h"
#include "inc/YieldExpressionWrapper.h"
#include "inc/BooleanLiteralWrapper.h"
#include "inc/NullLiteralWrapper.h"
#include "inc/NumberLiteralWrapper.h"
#include "inc/RegExpLiteralWrapper.h"
#include "inc/StringLiteralWrapper.h"
#include "inc/AssignmentPropertyWrapper.h"
#include "inc/ArrayPatternWrapper.h"
#include "inc/AssignmentPatternWrapper.h"
#include "inc/ObjectPatternWrapper.h"
#include "inc/RestElementWrapper.h"
#include "inc/BlockStatementWrapper.h"
#include "inc/BreakStatementWrapper.h"
#include "inc/ContinueStatementWrapper.h"
#include "inc/DebuggerStatementWrapper.h"
#include "inc/EmptyStatementWrapper.h"
#include "inc/ExpressionStatementWrapper.h"
#include "inc/ForInStatementWrapper.h"
#include "inc/ForStatementWrapper.h"
#include "inc/IfStatementWrapper.h"
#include "inc/LabeledStatementWrapper.h"
#include "inc/ReturnStatementWrapper.h"
#include "inc/SwitchStatementWrapper.h"
#include "inc/ThrowStatementWrapper.h"
#include "inc/TryStatementWrapper.h"
#include "inc/WhileStatementWrapper.h"
#include "inc/WithStatementWrapper.h"
#include "inc/ClassDeclarationWrapper.h"
#include "inc/ExportSpecifierWrapper.h"
#include "inc/FunctionDeclarationWrapper.h"
#include "inc/ExportAllDeclarationWrapper.h"
#include "inc/ExportDefaultDeclarationWrapper.h"
#include "inc/VariableDeclarationWrapper.h"
#include "inc/ForOfStatementWrapper.h"
#include "inc/DoWhileStatementWrapper.h"
#include "inc/ImportDefaultSpecifierWrapper.h"
#include "inc/ImportNamespaceSpecifierWrapper.h"
#include "inc/ImportSpecifierWrapper.h"
#define DECLARE_NAPI_METHOD(name, func) \
  { name, 0, func, 0, 0, 0, napi_default, 0 } 

napi_value Init(napi_env env, napi_value exports){
    columbus::javascript::asg::addon::Factory::Init(env, exports);
  columbus::javascript::asg::addon::SystemWrapper::Init(env, exports);
  columbus::javascript::asg::addon::CommentWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ModuleDeclarationWrapper::Init(env, exports);
  columbus::javascript::asg::addon::VariableDeclaratorWrapper::Init(env, exports);
  columbus::javascript::asg::addon::PropertyWrapper::Init(env, exports);
  columbus::javascript::asg::addon::SpreadElementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::SuperWrapper::Init(env, exports);
  columbus::javascript::asg::addon::TemplateElementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::CatchClauseWrapper::Init(env, exports);
  columbus::javascript::asg::addon::FunctionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::SwitchCaseWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ClassBodyWrapper::Init(env, exports);
  columbus::javascript::asg::addon::MethodDefinitionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ProgramWrapper::Init(env, exports);
  columbus::javascript::asg::addon::IdentifierWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ExportNamedDeclarationWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ImportDeclarationWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ArrayExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ArrowFunctionExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::AssignmentExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::AwaitExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::BinaryExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::CallExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ClassExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ConditionalExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::FunctionExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::LogicalExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::MemberExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::MetaPropertyWrapper::Init(env, exports);
  columbus::javascript::asg::addon::NewExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ObjectExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::SequenceExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::TaggedTemplateExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::TemplateLiteralWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ThisExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::UnaryExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::UpdateExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::YieldExpressionWrapper::Init(env, exports);
  columbus::javascript::asg::addon::BooleanLiteralWrapper::Init(env, exports);
  columbus::javascript::asg::addon::NullLiteralWrapper::Init(env, exports);
  columbus::javascript::asg::addon::NumberLiteralWrapper::Init(env, exports);
  columbus::javascript::asg::addon::RegExpLiteralWrapper::Init(env, exports);
  columbus::javascript::asg::addon::StringLiteralWrapper::Init(env, exports);
  columbus::javascript::asg::addon::AssignmentPropertyWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ArrayPatternWrapper::Init(env, exports);
  columbus::javascript::asg::addon::AssignmentPatternWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ObjectPatternWrapper::Init(env, exports);
  columbus::javascript::asg::addon::RestElementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::BlockStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::BreakStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ContinueStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::DebuggerStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::EmptyStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ExpressionStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ForInStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ForStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::IfStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::LabeledStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ReturnStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::SwitchStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ThrowStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::TryStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::WhileStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::WithStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ClassDeclarationWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ExportSpecifierWrapper::Init(env, exports);
  columbus::javascript::asg::addon::FunctionDeclarationWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ExportAllDeclarationWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ExportDefaultDeclarationWrapper::Init(env, exports);
  columbus::javascript::asg::addon::VariableDeclarationWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ForOfStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::DoWhileStatementWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ImportDefaultSpecifierWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ImportNamespaceSpecifierWrapper::Init(env, exports);
  columbus::javascript::asg::addon::ImportSpecifierWrapper::Init(env, exports);
    return exports;
}

NAPI_MODULE(javascriptaddon, Init)              
