

# Expected input variables:
#   INPUT_FILE_NAME
#   OUTPUT_FILE_NAME
#   TEMPLATE_VARIABLE_NAME
#   TEMPLATE_VARIABLE_VALUE_FILE

file (READ ${TEMPLATE_VARIABLE_VALUE_FILE} ${TEMPLATE_VARIABLE_NAME})
string (STRIP "${${TEMPLATE_VARIABLE_NAME}}" ${TEMPLATE_VARIABLE_NAME})
configure_file(${INPUT_FILE_NAME} ${OUTPUT_FILE_NAME})
