

set (COLUMBUS_64BIT FALSE)

if (((CMAKE_SYSTEM_NAME STREQUAL Windows) AND CMAKE_CL_64) OR (CMAKE_SYSTEM_PROCESSOR STREQUAL x86_64))
  set (COLUMBUS_64BIT TRUE)
endif ()

if (COLUMBUS_64BIT)
  set (COLUMBUS_PLATFORM_NAME x64)
  set (VS_PLATFORM x64)
  set (VS_PLATFORM_DIR x64/)
  set (PYTHON_PLATFORM_NAME amd64)
else ()
  set (COLUMBUS_PLATFORM_NAME x86)
  set (VS_PLATFORM WIN32)
  set (VS_PLATFORM_DIR )
  set (PYTHON_PLATFORM_NAME win32)
endif ()

if (CMAKE_SYSTEM_NAME STREQUAL Windows)
  set (SCRIPT_EXT .bat)
elseif (CMAKE_SYSTEM_NAME STREQUAL Linux)
  set (SCRIPT_EXT .sh)
  set (COMMAND_PREFIX ./)
else ()
  message (FATAL_ERROR "Unknown system:${CMAKE_SYSTEM_NAME}")
endif()

set (COLUMBUS_PLATFORM_DEPENDENT_DIR ${COLUMBUS_PLATFORM_NAME})
set (EXE ${CMAKE_EXECUTABLE_SUFFIX})
